[package]
name = "bdk-ffi"
version = "0.29.0"
authors = ["Steve Myers <steve@notmandatory.org>", "Sudarsan Balaji <sudarsan.balaji@artfuldev.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "bdkffi"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["uniffi/cli"]

[dependencies]
bdk = { git = "https://github.com/jurvis/bdk.git", branch = "log-electrum-call-count-2", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc"] }
uniffi = { version = "0.23.0" }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.23.0", features = ["bindgen-tests"] }
assert_matches = "1.5.0"
